City: Columbia
Country: United States
Description: Entry for hosted CE submitting to University of Missouri clusters
Latitude: 38.9410516354836
Longitude: -92.32573369440686
State: MO
Zipcode: '65211'