# LongName is the expanded name of the site
LongName: University of Campinas - Physics Institute - Computer Center Professor John David Rogers
# Description is a brief description of your site
Description: Computer Center building of the UNICAMP/IFGW

# If you have an up-to-date local git clone, fill ID with the output from `bin/next_site_id`
# Otherwise, leave it blank and we will fill in the appropriate value for you.
ID: 10291

# AddressLine1 is the street address of the site
AddressLine1: Pitágoras Street, 2 - Cidade Universitária, Campinas - SP
### AddressLine2 (optional) is the second line of the street address
# AddressLine2: Room 101
# City is the city the site is located in
City: Campinas

# Country is the country the site is located in
Country: Brazil
### State (optional) is the state or province the site is located in
State: Sao Paulo
### Zipcode (optional) is the zipcode/postal code of the site
Zipcode: "13083-859"

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: -22.815931210560226
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -47.067740869316836
