LongName: DIII-D National Fusion Facility
Description:  Fusion Data Platform
AddressLine1: 3483 Dunhill St.
City: San Diego
Country: US
Latitude: 32.90246879605678
Longitude: -117.2283010938664
State: CA
Zipcode: 92121